--- # Testing Todd's POC

- name: List objects from all the buckets
  hosts: localhost
  vars:
    # common vars
    v_bucket_name: "MyFirstBucket"
    #v_bucket_name: "bucket-tgrimmet"
    v_object_name: "OAL_ANSIBLE_POC"
    v_namespace_name: "axadba4rfl4d"
    #ansible_python_interpreter: /bin/python3.6
    #interpreter_python_fallback: /bin/python3.6
    #compartment_id: "{{ lookup('env', 'SAMPLE_COMPARTMENT_OCID') }}"
    #namespace_name: "{{ lookup('env', 'SAMPLE_OBJECT_NS_NAME') }}"
    #v_compartment_id: "ocid1.compartment.oc1..aaaaaaaa5wbm2hmoebym3mbgqhjjhyuy3kmtjx6fszcbtmcb6mnrsbbkdofa"
    #    compartment_id: "{{ v_compartment_id }}"
    #v_namespace_name: "corpssononprod"
  tasks:
  - name: Create/upload an object without multipart and parallel upload
    oci_object:
       bucket_name: "{{ v_bucket_name }}"
       namespace_name: "{{ v_namespace_name }}"
       object: "{{ v_object_name }}"
       state: present
       src: glances.conf 
       multipart_upload: False
       parallel_uploads: False
    register: result
